version: "3.8"
services:
  ipsc_lipidtox:
    build: .
    container_name: ipsc_lipidtox_container
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
